---
# defaults file for spacewalk-client--role
spacewalk_admin_email: root@localhost
spacewalk_hostname: spacewalk-server
spacewalk_ip: 10.102.1.101
gpg_pubkeyfileexport: spacewalk.asc


# Path to the environment file
environment_file: /etc/environment
# The environment file owner
environment_file_owner: root
# The environment file group
environment_file_group: root